### ISSUE TITLE
Erro ao testar o código que baixei

### ISSUE THREAD

**Issue by antonnioliveira** [PacktPublishing/Python-Programming-Blueprints#12]
Olá estou tentando executar o app Spotify, fiz tudo direitinho e estou recebendo está mensagem poderia me da uma luz, e parabéns pelo livro :D!

PS C:\Users\elton\Downloads\Python-Programming-Blueprints-master\Chapter02\musicterminal> python app.pyTraceback (most recent call last):
  File "app.py", line 105, in <module>
    wrapper(main)
  File "C:\Users\elton\AppData\Local\Programs\Python\Python36-32\lib\curses\__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "app.py", line 57, in main
    albums_panel.update()
  File "C:\Users\elton\Downloads\Python-Programming-Blueprints-master\Chapter02\musicterminal\client\menu.py", line 79, in update
    curses.A_REVERSE if item.selected else curses.A_NORMAL)
_curses.error: addwstr() returned ERR

**Comment by dfurtado** [comment]
Ola @antonnioliveira ,

Muito obrigado por comprar o meu livro, eu coloquei muitas horas de trabalho neste projeto entao eu espero que voce esteja gostando. Desculpe a demora para responder, foi final de semana prolongado aqui na Suécia.
Eu percebi que voce esta tentado executar esse projeto no Windows. O problem é que Python para Windows não include `curses` então esse examplo infelizmente nao ira funcionar no Windows. Tem algums projetos que säo uma alternativa ao module `curses` mas esses projetos também näo funcionam 100%.

Na documentacao do `curses` module https://docs.python.org/3.6/howto/curses.html voce tem:

> The Windows version of Python doesn’t include the curses module. A ported version called UniCurses is available. You could also try the Console module written by Fredrik Lundh, which doesn’t use the same API as curses but provides cursor-addressable text output and full support for mouse and keyboard input.

//Daniel F.
