### ISSUE TITLE
Weatherterm and weather.com change? 

### ISSUE THREAD

**Issue by drivercoin** [PacktPublishing/Python-Programming-Blueprints#44]
I'm having trouble running the code.  It says:
weather_com_parser.py", line 49, in _parse
    for item in container]
TypeError: 'NoneType' object is not iterable

The container is None when printing it while running.
I went through the weather.com and the following link:
https://weather.com/weather/today/l/SWXX2372:1:SW
It does not show the class anymore with the section
"today_nowcard-container"
Did weather.com change their page source code or how they create
their pages now?

**Comment by pythonyalfa** [comment]
When i tried that app it didn't work for me either just my two centsOn Jun 6, 2022 6:31 PM, drivercoin ***@***.***> wrote:
I'm having trouble running the code.  It says:
weather_com_parser.py", line 49, in _parse
for item in container]
TypeError: 'NoneType' object is not iterable
The container is None when printing it while running.
I went through the weather.com and the following link:
https://weather.com/weather/today/l/SWXX2372:1:SW
It does not show the class anymore with the section
"today_nowcard-container"
Did weather.com change their page source code or how they create
their pages now?

**Comment by shruthis-shetty** [comment]
Hi @pythonyalfa and @drivercoin ,

The code has become outdated. The content of the site [weather.com](https://protect-eu.mimecast.com/s/Hj_NCvYzxtGKnQf57DZ4?domain=weather.com) they have changed the markup on their page and the code on the book is no longer working as intended.
