### ISSUE TITLE
TypeError: object() takes no parameters

### ISSUE THREAD

**Issue by armaanreza** [PacktPublishing/Python-Programming-Blueprints#5]
I am getting "TypeError: object() takes no parameters" after running following command:

python -m weatherterm -u Fahrenheit -a USNY1192:1:US -p WeatherComParser -td

I could not solve the problem after several hours of checking every bit of the codes in the book and finally submitted to stackoverflow [https://stackoverflow.com/questions/49393703/typeerror-object-takes-no-parameters-python-3-6-3](url) to possibly free myself from frustrations.

Any help would be highly appreciated.

Kind regards

**Comment by dfurtado** [comment]
Hi @armaanreza 

Sorry to hear that you are having problems with this example. I just fetched the code that is here in the repository and I couldn't reproduce the error. I'm running the exactly the same Python version as you 3.6.3. Do you have phantomJS in `phantonjs/bin/`?

Looking at the call stack that you posted on StackOverflow, it seems to me that it is something wrong in the Request class. The Request class in this example takes one parameter, and it should look like this:

```python
class Request:
    def __init__(self, base_url):
        self._driver_path = os.path.join(os.curdir, 'phantomjs/bin/phantomjs')
        self._base_url = base_url
        self._driver = webdriver.PhantomJS(self._driver_path)

    def fetch_data(self, forecast, area):
        url = self._base_url.format(forecast=forecast, area=area)
        self._driver.get(url)

        if self._driver.title == '404 Not Found':
            error_message = ('Could not find the area that you '
                             'searching for')
            raise Exception(error_message)

        return self._driver.page_source
``` 

Let me know if that works for you.

Best regards

**Comment by armaanreza** [comment]
Dear Daniel,

Thank you so much for leading me to the correct file (request.py) and solve
the problem. There was a typo in my file because I have typed all the codes
myself and did not just copy paste. Now, the app is working. Thank you once
again for your prompt response.

Regards,
Syed

**Comment by dfurtado** [comment]
Hi @armaanreza 
I am glad to help!!
