### ISSUE TITLE
musicterminal - Not Playing Song

### ISSUE THREAD

**Issue by armaanreza** [PacktPublishing/Python-Programming-Blueprints#7]
Hi @dfurtado 

I can get through the 'list of albums --> list of tracks' but unable to play song. When I clicked on the track, the song didn't play.

I have been looking for all possible errors but couldn't find one. Appreciate if you please have a look into my repo https://github.com/armaanreza/musicterminal/tree/music-app and resolve the issue.

Regards

**Comment by dfurtado** [comment]
Hi @armaanreza 

I think it might be that the API didn't find your active device (the Spotify client that you are currently listening to music). Before selecting a song in the application that you have built, try playing a song in the Spotify client (it can be the desktop client, your mobile phone or the web).
I had a similar problem while building the application and the solution was the start off by playing first on the Spotify client and then using the app to change songs.

Let me know if that works for you.

Best regards

**Comment by armaanreza** [comment]
Hi @dfurtado 

Thank you so much! 👍  

It works while the Spotify desktop app is running in background. Greatly appreciate your support.

Regards

**Comment by dfurtado** [comment]
Hi @armaanreza 

You're very welcome, I'm always glad to help!

Best Regards
