### ISSUE TITLE
nvm installation 

### ISSUE THREAD

**Issue by armaanreza** [PacktPublishing/Python-Programming-Blueprints#8]
Hi @dfurtafo

Do you want me to install nvm in virtual environment? I followed the link to install nvm script but I can't access nvm command within virtual environment. It says nvm not found. Also, after tried to install nvm in virtual environment, my virtual environment terminal prompt has changed to..bash 3.2$ and it doesn't show project folder name any more. 

Appreciate your advice. 

Regards

**Comment by dfurtado** [comment]
Hi @armaanreza ,

You don't need to install _nvm_ within the virtual environment. _NVM_ is the _NodeJS_ version manager and it is used to install _NodeJS_ in our system in a simpler manner. It will also give you more control of the _NodeJS_ version that you have installed, and lastly, it will be easier for you to switch between different versions.

The _NVM_ tool will only make your life easier when working with _NodeJS_ however you don't need to use it, if you don't want to, you can just download and install _NodeJS_ following the instructions at https://nodejs.org/en/

If you want to try _NVM_ you can follow the instructions on this site https://github.com/creationix/nvm

But, answering your question, _NVM_ is not a Python package so you don't need to install it in our virtual environment.

**Comment by armaanreza** [comment]
Thanks Daniel. Your message explains it all.

**Comment by dfurtado** [comment]
Hi @armaanreza ,

Nice! Glad to help!!

Have a great day!
